import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <div className="min-h-screen">
          <Navbar className="mx-40" />
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </div>
        <Footer id="contact" className="px-40" />
      </body>
    </html>
  );
}
